USE [master]
GO

/****** Object:  Database [FixTheIncident]    Script Date: 2017/07/18 12:31:33 PM ******/
CREATE DATABASE [FixTheIncident]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FixTheIncident', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\FixTheIncident.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FixTheIncident_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\FixTheIncident_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [FixTheIncident] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FixTheIncident].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FixTheIncident] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FixTheIncident] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FixTheIncident] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FixTheIncident] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FixTheIncident] SET ARITHABORT OFF 
GO

ALTER DATABASE [FixTheIncident] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FixTheIncident] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FixTheIncident] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FixTheIncident] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FixTheIncident] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FixTheIncident] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FixTheIncident] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FixTheIncident] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FixTheIncident] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FixTheIncident] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FixTheIncident] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FixTheIncident] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FixTheIncident] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FixTheIncident] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FixTheIncident] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FixTheIncident] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FixTheIncident] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FixTheIncident] SET RECOVERY FULL 
GO

ALTER DATABASE [FixTheIncident] SET  MULTI_USER 
GO

ALTER DATABASE [FixTheIncident] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FixTheIncident] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FixTheIncident] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FixTheIncident] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FixTheIncident] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FixTheIncident] SET QUERY_STORE = OFF
GO

USE [FixTheIncident]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [FixTheIncident] SET  READ_WRITE 
GO

